/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TelasNovas;

import DAO.AgendaDAO;
import DAO.ContatoDAO;
import DTO.AgendaDTO;
import DTO.ContatoDTO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ulissesweyl
 */
public class TelaAgenda extends javax.swing.JFrame {
private TelaAgenda telaAgenda;
private AgendaDTO agendas;
    /**
     * Creates new form TelaAgenda
     */
    public TelaAgenda() {
        initComponents();
        carregarListaAgenda();
    }
    
        private void carregarListaAgenda() {
        AgendaDAO agendaDAO = new AgendaDAO();
        
        List<AgendaDTO> listaagenda = new ArrayList<>();
        listaagenda = agendaDAO.listarAgendas();       

     
        DefaultTableModel modelo = new javax.swing.table.DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Nome");


        if (listaagenda.size() == 0) {
            modelo.addRow(new String[]{"Sem dados",
                        null});
        }
        
        for (int i = 0; i < listaagenda.size(); i++) {
            AgendaDTO p = listaagenda.get(i);

            // Alimenta as linhas de dados  
            modelo.addRow(new Object[]{
                        p.getIdAgenda(),
                        p.getNomeAgenda()});
        }

        tabelaListaAgenda.setModel(modelo);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelTituloAgenda = new javax.swing.JPanel();
        labelTiluloAgenda = new javax.swing.JLabel();
        painelGerenciaAgenda = new javax.swing.JPanel();
        painelGerenciaAcao = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botaoSalvarAgenda = new javax.swing.JButton();
        nomeAgenda = new javax.swing.JTextField();
        painelListaAgenda = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaListaAgenda = new javax.swing.JTable();
        painelBotoesAgenda = new javax.swing.JPanel();
        botaoEditarAgenda = new javax.swing.JButton();
        botaoExcluirAgenda = new javax.swing.JButton();
        botaoFecharAgenda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agendas");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(480, 320));
        setResizable(false);

        painelTituloAgenda.setPreferredSize(new java.awt.Dimension(480, 40));

        labelTiluloAgenda.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 18)); // NOI18N
        labelTiluloAgenda.setText("Gerenciar Agendas");
        painelTituloAgenda.add(labelTiluloAgenda);

        getContentPane().add(painelTituloAgenda, java.awt.BorderLayout.NORTH);

        painelGerenciaAgenda.setBorder(javax.swing.BorderFactory.createTitledBorder("Gerenciar"));
        painelGerenciaAgenda.setLayout(new java.awt.BorderLayout());

        painelGerenciaAcao.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Agenda");
        painelGerenciaAcao.add(jLabel1, java.awt.BorderLayout.LINE_START);

        botaoSalvarAgenda.setText("Salvar");
        botaoSalvarAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarAgendaActionPerformed(evt);
            }
        });
        painelGerenciaAcao.add(botaoSalvarAgenda, java.awt.BorderLayout.LINE_END);
        painelGerenciaAcao.add(nomeAgenda, java.awt.BorderLayout.CENTER);

        painelGerenciaAgenda.add(painelGerenciaAcao, java.awt.BorderLayout.NORTH);

        painelListaAgenda.setPreferredSize(new java.awt.Dimension(480, 180));

        tabelaListaAgenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelaListaAgenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabelaListaAgendaMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaListaAgenda);

        painelListaAgenda.add(jScrollPane1);

        painelGerenciaAgenda.add(painelListaAgenda, java.awt.BorderLayout.CENTER);

        getContentPane().add(painelGerenciaAgenda, java.awt.BorderLayout.CENTER);

        botaoEditarAgenda.setText("Editar");
        botaoEditarAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditarAgendaActionPerformed(evt);
            }
        });
        painelBotoesAgenda.add(botaoEditarAgenda);

        botaoExcluirAgenda.setText("Excluir");
        botaoExcluirAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirAgendaActionPerformed(evt);
            }
        });
        painelBotoesAgenda.add(botaoExcluirAgenda);

        botaoFecharAgenda.setText("Fechar");
        botaoFecharAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFecharAgendaActionPerformed(evt);
            }
        });
        painelBotoesAgenda.add(botaoFecharAgenda);

        getContentPane().add(painelBotoesAgenda, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoFecharAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFecharAgendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoFecharAgendaActionPerformed

    private void botaoSalvarAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarAgendaActionPerformed
        // TODO add your handling code here:
        String nome = this.nomeAgenda.getText();
       
        if (this.agendas != null){
        AgendaDTO agendaDTO = new AgendaDTO();
        AgendaDAO agendaDAO = new AgendaDAO();
        agendaDTO.setIdAgenda(this.agendas.getIdAgenda());
        agendaDTO.setNomeAgenda(nome);
        System.out.println(nome);
        System.out.println(this.agendas.getIdAgenda()); 
        agendaDAO.atualizar(agendaDTO);
        JOptionPane.showMessageDialog(null, 
                    "Cadastro Atualizado com sucesso", 
                    "Cadastro", JOptionPane.PLAIN_MESSAGE);
        this.agendas = null;
        carregarListaAgenda();
        } else {
          System.out.println(nome);
            AgendaDTO agendaDTO = new AgendaDTO();
            AgendaDAO agendaDAO = new AgendaDAO();
            agendaDTO.getIdAgenda();
            agendaDTO.setNomeAgenda(nome);
            agendaDAO.inserir(agendaDTO);
            JOptionPane.showMessageDialog(null, 
                    "Cadastro sALVO com sucesso", 
                    "Cadastro", JOptionPane.PLAIN_MESSAGE);   
            
            carregarListaAgenda();
        }
        
    }//GEN-LAST:event_botaoSalvarAgendaActionPerformed

    private void botaoExcluirAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirAgendaActionPerformed
        // TODO add your handling code here:
        try{
            AgendaDAO agenda = new AgendaDAO();
            int linha = tabelaListaAgenda.getSelectedRow();   
            int coluna = tabelaListaAgenda.getColumnModel().getColumnIndex("ID"); 
            Object value = tabelaListaAgenda.getValueAt(linha, coluna);  
            Integer numero = (Integer)value;
            System.out.println(numero);
            agenda.remover(numero);
                    
        carregarListaAgenda();
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, "Selecione uma Agenda!");
        }
    }//GEN-LAST:event_botaoExcluirAgendaActionPerformed

    private void tabelaListaAgendaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaListaAgendaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelaListaAgendaMousePressed

    private void botaoEditarAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditarAgendaActionPerformed
        // TODO add your handling code here:
    try {
            
            int linha = tabelaListaAgenda.getSelectedRow();
            AgendaDAO agendaDAO = new AgendaDAO();
            
            AgendaDTO c = agendaDAO.listarAgendas().get(linha);
            c.getIdAgenda();
            c.getNomeAgenda();
            nomeAgenda.setText(c.getNomeAgenda());
            //agendaDAO.atualizar(c);
            AtualizaAgenda(this, c);
            //carregarListaAgenda();
            } catch (Exception e) {
            
            JOptionPane.showMessageDialog(this, "Selecione um Contato!");
            //botaoEditarContato.setEnabled(false);
        }
    }//GEN-LAST:event_botaoEditarAgendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAgenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoEditarAgenda;
    private javax.swing.JButton botaoExcluirAgenda;
    private javax.swing.JButton botaoFecharAgenda;
    private javax.swing.JButton botaoSalvarAgenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTiluloAgenda;
    private javax.swing.JTextField nomeAgenda;
    private javax.swing.JPanel painelBotoesAgenda;
    private javax.swing.JPanel painelGerenciaAcao;
    private javax.swing.JPanel painelGerenciaAgenda;
    private javax.swing.JPanel painelListaAgenda;
    private javax.swing.JPanel painelTituloAgenda;
    private javax.swing.JTable tabelaListaAgenda;
    // End of variables declaration//GEN-END:variables

    private void AtualizaAgenda(TelaAgenda telaAgenda, AgendaDTO agendas){
        this.agendas = agendas;
        
    //nomeAgenda.setText(agendas.getNomeAgenda());
    }
}
