/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TelasNovas;

import DAO.AgendaDAO;
import DAO.ContatoDAO;
import DTO.AgendaDTO;
import DTO.ContatoDTO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author ulissesweyl
 */
public class TelaContato extends javax.swing.JFrame {
    private TelaRelatorio telaRelatorio;
    private ContatoDTO contato;

    /**
     * Creates new form telaContato
     */
    public TelaContato() {
        initComponents();
    }
    public TelaContato(TelaRelatorio telaRelatorio, ContatoDTO c) {
        this();
        
        this.telaRelatorio = telaRelatorio;
        this.contato = c;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelTitulo = new javax.swing.JPanel();
        labelTituloContato = new javax.swing.JLabel();
        painelFormulario = new javax.swing.JPanel();
        labelNomeContato = new javax.swing.JLabel();
        nomeContato = new javax.swing.JTextField();
        labelEnderecoContato = new javax.swing.JLabel();
        enderecoContato = new javax.swing.JTextField();
        labelTelefoneContato = new javax.swing.JLabel();
        telefoneContato = new javax.swing.JTextField();
        labelEmailContato = new javax.swing.JLabel();
        emailContato = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        nomeAgenda = new javax.swing.JComboBox();
        painelBotoesContato = new javax.swing.JPanel();
        botaoSalvarContato = new javax.swing.JButton();
        botaoLimparContato = new javax.swing.JButton();
        botaoFecharContato = new javax.swing.JButton();
        barraMenu = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        menuCadastroNovo = new javax.swing.JMenuItem();
        menuCadastroSalvar = new javax.swing.JMenuItem();
        menuCadastroFechar = new javax.swing.JMenuItem();
        menuAgenda = new javax.swing.JMenu();
        menuAgendaAdicionar = new javax.swing.JMenuItem();
        menuRelatorio = new javax.swing.JMenu();
        menuRelatorioMostrar = new javax.swing.JMenuItem();
        menuAjuda = new javax.swing.JMenu();
        menuAjudaSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Contato");
        setName("frameContato"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        painelTitulo.setPreferredSize(new java.awt.Dimension(480, 40));

        labelTituloContato.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 18)); // NOI18N
        labelTituloContato.setText("Cadastro de Contato");
        painelTitulo.add(labelTituloContato);

        getContentPane().add(painelTitulo, java.awt.BorderLayout.NORTH);

        painelFormulario.setBorder(javax.swing.BorderFactory.createTitledBorder("Formulário"));
        painelFormulario.setPreferredSize(new java.awt.Dimension(480, 200));
        painelFormulario.setLayout(new java.awt.GridLayout(5, 2, 0, 5));

        labelNomeContato.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 16)); // NOI18N
        labelNomeContato.setText(" Nome:");
        painelFormulario.add(labelNomeContato);

        nomeContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeContatoActionPerformed(evt);
            }
        });
        painelFormulario.add(nomeContato);

        labelEnderecoContato.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 16)); // NOI18N
        labelEnderecoContato.setText(" Endereço:");
        painelFormulario.add(labelEnderecoContato);
        painelFormulario.add(enderecoContato);

        labelTelefoneContato.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 16)); // NOI18N
        labelTelefoneContato.setText(" Telefone:");
        painelFormulario.add(labelTelefoneContato);
        painelFormulario.add(telefoneContato);

        labelEmailContato.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 16)); // NOI18N
        labelEmailContato.setText(" E-Mail:");
        painelFormulario.add(labelEmailContato);
        painelFormulario.add(emailContato);

        jLabel1.setText("jLabel1");
        painelFormulario.add(jLabel1);

        nomeAgenda.setName(""); // NOI18N
        nomeAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeAgendaActionPerformed(evt);
            }
        });
        painelFormulario.add(nomeAgenda);

        getContentPane().add(painelFormulario, java.awt.BorderLayout.CENTER);

        painelBotoesContato.setPreferredSize(new java.awt.Dimension(480, 40));

        botaoSalvarContato.setText("Salvar");
        botaoSalvarContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarContatoActionPerformed(evt);
            }
        });
        painelBotoesContato.add(botaoSalvarContato);

        botaoLimparContato.setText("Limpar");
        botaoLimparContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimparContatoActionPerformed(evt);
            }
        });
        painelBotoesContato.add(botaoLimparContato);

        botaoFecharContato.setText("Fechar");
        botaoFecharContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFecharContatoActionPerformed(evt);
            }
        });
        painelBotoesContato.add(botaoFecharContato);

        getContentPane().add(painelBotoesContato, java.awt.BorderLayout.SOUTH);

        menuCadastro.setText("Cadastro");

        menuCadastroNovo.setText("Novo");
        menuCadastroNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroNovoActionPerformed(evt);
            }
        });
        menuCadastro.add(menuCadastroNovo);

        menuCadastroSalvar.setText("Salvar");
        menuCadastroSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroSalvarActionPerformed(evt);
            }
        });
        menuCadastro.add(menuCadastroSalvar);

        menuCadastroFechar.setText("Fechar");
        menuCadastro.add(menuCadastroFechar);

        barraMenu.add(menuCadastro);

        menuAgenda.setText("Agenda");

        menuAgendaAdicionar.setText("Adicionar");
        menuAgendaAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAgendaAdicionarActionPerformed(evt);
            }
        });
        menuAgenda.add(menuAgendaAdicionar);

        barraMenu.add(menuAgenda);

        menuRelatorio.setText("Relatório");

        menuRelatorioMostrar.setText("Listar Contatos");
        menuRelatorioMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRelatorioMostrarActionPerformed(evt);
            }
        });
        menuRelatorio.add(menuRelatorioMostrar);

        barraMenu.add(menuRelatorio);

        menuAjuda.setText("Ajuda");

        menuAjudaSobre.setText("Sobre...");
        menuAjuda.add(menuAjudaSobre);

        barraMenu.add(menuAjuda);

        setJMenuBar(barraMenu);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nomeContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeContatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeContatoActionPerformed

    private void botaoLimparContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimparContatoActionPerformed
        // TODO add your handling code here:
        LimparCampos();
    }//GEN-LAST:event_botaoLimparContatoActionPerformed

    private void botaoFecharContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFecharContatoActionPerformed
        // TODO add your handling code here:
        if (this.contato != null) {
        dispose();
        }else{
        System.exit(0);
        }
    }//GEN-LAST:event_botaoFecharContatoActionPerformed

    private void menuCadastroSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroSalvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCadastroSalvarActionPerformed

    private void menuRelatorioMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRelatorioMostrarActionPerformed
        // TODO add your handling code here:
        TelaRelatorio telaRel = new TelaRelatorio();
        telaRel.setVisible(true);
    }//GEN-LAST:event_menuRelatorioMostrarActionPerformed

    private void menuCadastroNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroNovoActionPerformed
        // TODO add your handling code here:
        LimparCampos();
    }//GEN-LAST:event_menuCadastroNovoActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        if (this.contato != null) {
            carregarProdutoNosCampos();
        }
        carregarCombo();
    }//GEN-LAST:event_formWindowActivated

    private void botaoSalvarContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarContatoActionPerformed
        // TODO add your handling code here:
        ContatoDAO contatoDAO = new ContatoDAO();
        ContatoDTO contatoDTO = new ContatoDTO();
        
        String nome = nomeContato.getText();
        String endereco = enderecoContato.getText();
        String telefone = telefoneContato.getText(); 
        String email = emailContato.getText(); 
//        int idAg = nomeAgenda.get
        AgendaDTO selecionado = (AgendaDTO) nomeAgenda.getSelectedItem(); 
        int codigo = selecionado.getIdAgenda(); 
        String agenda = selecionado.getNomeAgenda();
        //ContatoDTO c = this.contato;
        

         if (this.contato == null) {
            System.out.println("Salvar aqui");
            contatoDTO.setNomeContato(nome);
            contatoDTO.setEnderecoContato(endereco);
            contatoDTO.setTelefoneContato(telefone);
            contatoDTO.setEmailContato(email);
            //contatoDTO.setNomeAgenda(agenda);
            
            contatoDAO.inserir(contatoDTO, codigo);
            JOptionPane.showMessageDialog(null, 
                    "Cadastro Salvo com sucesso", 
                    "Cadastro", JOptionPane.PLAIN_MESSAGE);
            LimparCampos();

        } else {
             botaoSalvarContato.setText("Alterar");
            int idContato = this.contato.getIdContato();

            contatoDTO.setNomeContato(nome);
            contatoDTO.setEnderecoContato(endereco);
            contatoDTO.setTelefoneContato(telefone);
            contatoDTO.setEmailContato(email);
            contatoDTO.setIdContato(idContato);
            contatoDTO.setIdAgenda(codigo);

            contatoDAO.atualizar(contatoDTO);
            JOptionPane.showMessageDialog(null, 
                    "Cadastro Atualizado com sucesso", 
                    "Alualizar", JOptionPane.PLAIN_MESSAGE);
            
            dispose();
 
        }
    }//GEN-LAST:event_botaoSalvarContatoActionPerformed

    private void menuAgendaAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAgendaAdicionarActionPerformed
        // TODO add your handling code here:
        TelaAgenda agenda = new TelaAgenda();
        agenda.setVisible(true);
    }//GEN-LAST:event_menuAgendaAdicionarActionPerformed

    private void nomeAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeAgendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeAgendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaContato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaContato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaContato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaContato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaContato().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JButton botaoFecharContato;
    private javax.swing.JButton botaoLimparContato;
    private javax.swing.JButton botaoSalvarContato;
    private javax.swing.JTextField emailContato;
    private javax.swing.JTextField enderecoContato;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelEmailContato;
    private javax.swing.JLabel labelEnderecoContato;
    private javax.swing.JLabel labelNomeContato;
    private javax.swing.JLabel labelTelefoneContato;
    private javax.swing.JLabel labelTituloContato;
    private javax.swing.JMenu menuAgenda;
    private javax.swing.JMenuItem menuAgendaAdicionar;
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JMenuItem menuAjudaSobre;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenuItem menuCadastroFechar;
    private javax.swing.JMenuItem menuCadastroNovo;
    private javax.swing.JMenuItem menuCadastroSalvar;
    private javax.swing.JMenu menuRelatorio;
    private javax.swing.JMenuItem menuRelatorioMostrar;
    private javax.swing.JComboBox nomeAgenda;
    private javax.swing.JTextField nomeContato;
    private javax.swing.JPanel painelBotoesContato;
    private javax.swing.JPanel painelFormulario;
    private javax.swing.JPanel painelTitulo;
    private javax.swing.JTextField telefoneContato;
    // End of variables declaration//GEN-END:variables

    private void carregarCombo(){
        
        AgendaDAO agendaDAO = new AgendaDAO();

        List<AgendaDTO> listaagenda = new ArrayList<>();
        listaagenda = agendaDAO.listarAgendas(); 
        //nomeAgenda.setModel(new DefaultComboBoxModel(listaagenda.toArray()));
        DefaultComboBoxModel cmb = (DefaultComboBoxModel) nomeAgenda.getModel();
        cmb.removeAllElements();
        for (int i = 0; i < listaagenda.size(); i++) {
            AgendaDTO agd = listaagenda.get(i);
            
            cmb.addElement(agd);

            //nomeAgenda.addItem(agd.getNomeAgenda());
        }
        if (this.contato != null){
        List<AgendaDTO> nomeAg = agendaDAO.pegacombo(this.contato.getIdAgenda());
        AgendaDTO ag = nomeAg.get(0);  
        cmb.setSelectedItem(ag);
        }
    
    // nomeAgenda.setModel(cmb);       
    }
    
    private void carregarProdutoNosCampos() {
       // AgendaDAO agendaDAO = new AgendaDAO();

        nomeContato.setText(this.contato.getNomeContato());
        enderecoContato.setText(this.contato.getEnderecoContato()+"");
        telefoneContato.setText(this.contato.getTelefoneContato()+"");
        emailContato.setText(this.contato.getEmailContato());
       // nomeAgenda.setSelectedItem(ag);
        botaoSalvarContato.setText("Alterar");
               
    }   
    
    private void LimparCampos() {
        nomeContato.setText("");
        enderecoContato.setText("");
        telefoneContato.setText("");
        emailContato.setText("");//To change body of generated methods, choose Tools | Templates.
    }
    
    
}
